# Site Info
title:              "Blog"
description:        "Some thoughts"
author_name:        "Christophe Brocas" # change this to your name
logo_url:           https://avatars0.githubusercontent.com/cbrocas # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://blog.brocas.org # main url
baseurl:            "" 
permalink:          /:year/:month/:day/:title/ # Post permalink
timezone:           Europe/Paris # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap



defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
